## https://golangci-lint.run/usage/configuration/

run:
  timeout: 1m

output:
  format: colored-line-number

linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
  disable:
    - ireturn
    - gochecknoglobals

linters-settings:
  exhaustruct:
    exclude:
      - ".*_test"
  paralleltest:
    ignore-missing: true
  wrapcheck:
    ignoreSigRegexps:
      - \.New.*Error\(
  godox:
    keywords:
      - TODO
      - FIXME
      - HACK
      - OPTIMIZE
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
