name: Releaser

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash

permissions:
  contents: write
  packages: write
  deployments: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.work"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update go-proxy index
        run: go list -m 'github.com/${{ github.repository }}@${{ github.ref_name }}'
        env:
          GO_PROXY: proxy.golang.org
